sudo: true

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq rake ruby-bundler bundler uml-utilities mtools iptables

before_script:
  - wget https://releases.hashicorp.com/vagrant/2.1.1/vagrant_2.1.1_x86_64.deb
  - sudo dpkg -i vagrant_2.1.1_x86_64.deb

scripts:
  - sudo .travis/test_uml_xenial.sh
